### ISSUE TITLE
The result is 200 but I can't make it work

### ISSUE THREAD

**Issue by suhaboncukcu** [devonbarrett/meteor-dropzone#12]
Hey, 

This template actually looks pretty nice and out of the box but I couldn't make it work on my local. 

I'm running meteor 1.0.3.1 with iron:router and trying to upload to the folder in my public folder. 

I've tried my fullpath like /Users/PATHTOPROJECT/public/upload
and I've tried http://localhost:3000/upload

But none of the above worked out for me. Could you confirm this project still works with the latest version of Meteor and iron:router?

**Comment by devonbarrett** [comment]
Hello,

Yes I can confirm this still works. If you gist the code you are using to handle uploads I can take a look for you?

**Comment by suhaboncukcu** [comment]
Thanks for the reply,

https://gist.github.com/suhaboncukcu/51c74cbf6c8818cb7ebb


Hope it helps, I really don't have much things. 

Best,

**Comment by devonbarrett** [comment]
Ah it looks like there is some confusion about what Dropzone is:

>Dropzone does not handle your file uploads on the server. You have to implement the code to receive and store the file yourself. See the section Server side implementation for more information.

There are a few ways to do that: 
- Posting to a route and handling it server side with Iron Router
- Using something like [cfs](https://github.com/CollectionFS/Meteor-cfs-collection)
- Posting to a third party (file server as a service) e.g. AWS S3

If you checkout some of the other closed issues there are some more comments on ways to go about this.

**Comment by suhaboncukcu** [comment]
Oh, I see.. 

Thanks for teaching me a lesson.
