### ISSUE TITLE
Not have URL just parse local files 

### ISSUE THREAD

**Issue by almogdesign** [devonbarrett/meteor-dropzone#16]
Is it possible not to have a URL and just parse a local file I only need to use papa parser for CSV to JSON

**Comment by devonbarrett** [comment]
Yes it is possible, you will need to create a Dropzone element using javascript(the rendered callback is the best place to do this) and then handle files using a custom [event handler](http://www.dropzonejs.com/#event-list).

If you have a look at some of the closed issues on the upstream Dropzone repo you will see similiar questions with better answers :smiley:
