### ISSUE TITLE
Unable to change or remove default "Drop files up upload (or click)" 

### ISSUE THREAD

**Issue by ogourment** [devonbarrett/meteor-dropzone#17]
I tried different things but could not get rid of the default "Drop files up upload (or click)" message.
The following works in the sense that the message gets inserted in the DOM:
```
    Dropzone.options.dropzone = {
      dictDefaultMessage: 'my message here'
    };
```
But the default message still appears instead of what is expected. I also tried `null`.

There's another way to make this work, according to the [doc](http://www.dropzonejs.com/#tips), which consists in putting "an element inside your dropzone element with the class `dz-message`  and dropzone will not create the message for you.". But this just isn't possible with `{{> dropzone}}`. I also tried inserting the element dynamically, to no avail.

I suspect there's a timing issue, where Dropzone looks for the option or message too early. When it does not yet see it, it inserts its default.

**Comment by guillaume-dev** [comment]
Hi, 

I have found a temporary solution.
You can hide the default message by attaching an event to your dropzone's parent template.

```
// media.html

<template name="media">
	{{> dropzone id='dropzone' clickable=true dictDefaultMessage='Custom message'}}
</template>

// media.js

Template.media.rendered = function() {
    $('#dropzone .dz-default').removeClass('dz-message');
}

```

Hope this help.

Guillaume

**Comment by ahm1d** [comment]
Hi,

The default message is stored in a png file within the meteor package.
The css attribute 'background-image' holds the URL pointing towards this file. By default, you'll have something like this : 

```css
background-image: url("packages/dbarrett_dropzonejs/lib/3.10.2/images/spritemap.png")`
```

If you want to get rid of it, you can use the init option in your js file :

```javascript
Meteor.Dropzone.options.init =
function() {
   $('#imgDropzone .dz-message').css('background-image','none'); // or specify your own URL
};
```

Hope it helps.
Cheers

**Comment by devonbarrett** [comment]
Sorry I missed the notifications for this. 

I have just upgraded the package to Dropzone v4.0.1 which is a lot less opinionated when it comes to styling. So it should be easier to customise it in the way you want.

**Comment by wjessop** [comment]
I'm having this issue too, I initialise Dropzone:

```js
var dz = new Dropzone("#spreadsheet_upload_dropzone", {
  url: "/spreadsheet-upload",
  paramName: "file", // The name that will be used to transfer the file
  maxFilesize: 100, // MB
  maxFiles: 1,
  acceptedFiles: ".xlsx",
  createImageThumbnails: false,
  addedfile: function(file) { console.log(file); },
  dictDefaultMessage: 'nope'
});
```

but I still end up with the "Drop files here to upload" message. If I edit the dropzone.js file directly and set dictDefaultMessage to "" in Dropzone.prototype.defaultOptions the message dissapears.

**Comment by VeRJiL** [comment]
If you are creating Dropzones Programmatically then you have to set your options like below:

```
    Dropzone.autoDiscover = false;

    profilePicture = new Dropzone('#profile-picture', {
        url: "/uploadPicture.php",

        // if you are using laravel ..., you dont need to put csrf in meta tag
        headers: {
            'X-CSRF-TOKEN': "{{ csrf_token() }}"
        },

        dictDefaultMessage: "Your default message Will work 100%",

        /other options
        paramName: "profile_picture",
        addRemoveLinks: true,
        maxFilesize: 1,
        maxFiles: 10,

        dictRemoveFile: "Remove",

    });
```


If you are using it like this, It wont work ...

   ```
 let myDropzone = new Dropzone("#profile-picture", {

        url: "/uploadPicture.php",
        // if you are using laravel ..., you dont need to put csrf in meta tag
        headers: {
            'X-CSRF-TOKEN': "{{ csrf_token() }}"
        },

    });

    myDropzone.options.profilePicture = {

        dictDefaultMessage: "This message not gonna work",

        paramName: "profile_picture",
    };
```
