### ISSUE TITLE
dropzone + microscope tutorial

### ISSUE THREAD

**Issue by dansurfs** [devonbarrett/meteor-dropzone#20]
hi devon, 

My name is Daniel. I am putting your dropzone package in the meteor microscope tutorial from Discover Meteor. I originally sought Carl Wosley's help. He was very kind to help me get the images to upload but the dropzone doesn't show and each image upload has a check and x beneath it. I think it's been a problem for the both of us. I have the project on git if you'd like to take a look. I could even add you as a collaborator? I'm trying to add the dropzone form in the post_submit.html
https://github.com/dansurfs/slurfing

**Comment by wuzhuzhu** [comment]
need answer too
