### ISSUE TITLE
Not able to catch the event after drag and drop 

### ISSUE THREAD

**Issue by harshal-shinde** [devonbarrett/meteor-dropzone#22]
Template

<template name="hello">
    {{> dropzone url='http://localhost:3000//upload' id='dropzoneDiv'  maxFiles=4
        addRemoveLinks='Delete' dictDefaultMessage="Upload file here" dictFallbackText=''}}
</template>

js file

Template.hello.helpers({
    upload: function() {
      return true;
    }
  });

  Template.dropzone.events({
    'drop #dropzoneDiv': function(e) {
      console.log("Event trigger");
    }
  });

when i am trying to upload the image it is not either going in upload function or dropzone event

Please provide how we can achieve this 

Thanks in advance

**Comment by RayFerr000** [comment]
Was this ever solved?

**Comment by devonbarrett** [comment]
AFAIK, this is a limitation of meteor's supported events. http://docs.meteor.com/#/full/eventmaps
