### ISSUE TITLE
how to configure Dropzone for S3 upload

### ISSUE THREAD

**Issue by teknomath** [devonbarrett/meteor-dropzone#3]
I want to use Dropzone to upload files to an S3 bucket, and while there is a meteorite package for S3 (https://atmosphere.meteor.com/package/s3), it doesn't seem to compose properly with Dropzone for Meteor.  There's also Knox for Meteor (https://atmosphere.meteor.com/package/knox), and there's a lot of discussion on the Dropzone.js project on how to configure it for S3 uploading -- but these methods don't appear to be conducive to working with Dropzone for Meteor.  

Can you provide an explanation of how to configure Dropzone for Meteor to upload to S3?  Better yet, since this seems to be a highly desirable feature for the original Dropzone.js project, can an S3 upload feature be added to Dropzone for Meteor?

**Comment by ccmeyers** [comment]
I'd also love some clarification on this :-) @devonbarrett

**Comment by komrad** [comment]
Me too!
