### ISSUE TITLE
Uncaught ReferenceError: UploadServer is not defined

### ISSUE THREAD

**Issue by hich-em** [devonbarrett/meteor-dropzone#31]
Uncaught ReferenceError: UploadServer is not defined

meteor add tomi:upload-server
                                                                                   
Changes to your project's package version selections:
                                              
tomi:upload-server  added, version 1.3.4      

                                              
tomi:upload-server: Upload server for Meteor. Allows to save and serve files from arbitrary directory
Hich-em123-3:xxx neutron92$ meteor add tomi:upload-server
tomi:upload-server without a version constraint has already been added.

**Comment by devonbarrett** [comment]
This seems like an issue with upload-server. Please open an issue at tomitrescak/meteor-uploads.
