### ISSUE TITLE
write file in subdirectories

### ISSUE THREAD

**Issue by slepit** [devonbarrett/meteor-dropzone#32]
Hi,

I am not able to figure out how to upload the files in subdirectories.
Let's say I have users on the website.
I want to have the pictures uploaded in their respective subfolder; say "/upload/user_id/".
Can we do that from client side javascript code ?

thnaks

**Comment by devonbarrett** [comment]
Dropzone is a client side library, and doesn't handle the actual writing of files to the file system. 

To do that you would have to follow something like this: https://github.com/devonbarrett/meteor-dropzone#example-for-upload-on-server

**Comment by slepit** [comment]
Thank you for your quick reply.

This is actually what I am doing. But I am not able to pass formdata to the server. I do not know how to pass those formdata.

**Comment by devonbarrett** [comment]
Its not something I've looked into, but I would start by binding to the [sending event](http://www.dropzonejs.com/#event-sending) to see what is included.

It may be that you have to manually add your properties to that request.
