### ISSUE TITLE
Usage : pass formdata to the getfilename function

### ISSUE THREAD

**Issue by slepit** [devonbarrett/meteor-dropzone#33]
hello,

how do you set a the formdata and how do you pass it to the server ?

thanks a lot

**Comment by devonbarrett** [comment]
You can bind to this event: http://www.dropzonejs.com/#event-sending
>Called just before each file is sent. Gets the xhr object and the formData objects as second and third parameters, so you can modify them (for example to add a CSRF token) or add additional data.
