### ISSUE TITLE
Acess template instance when addedfile

### ISSUE THREAD

**Issue by lightsnow0** [devonbarrett/meteor-dropzone#35]
I execute some code after the addedfile event which works fine, but in my function i  need to give a function the template parameter. I don't know why but  it seems like in dropzone events is not this template parameter ? So how can i still use it ?

**Comment by devonbarrett** [comment]
Dropzone events are handled outside of the normal template events, which is why they do not include a reference to the template instance.

However, you could use `Blaze.getView(yourDropzoneElement)` [documentation](http://blazejs.org/api/blaze.html#Blaze-getView) to get the view instance.
